### ISSUE TITLE
How can I use this library with gradle project?

### ISSUE THREAD

**Issue by spkingr** [yole/jkid#4]
Is the only way to use this library is to download the source code to my project? Or can I include it in my gradle project? Thanks!

**Comment by yole** [comment]
You can use this library in your gradle project using [jitpack.io](https://jitpack.io/).

**Comment by spkingr** [comment]
Ok, thanks!

**Comment by InspectorZheleshka** [comment]
> Is the only way to use this library is to download the source code to my project? Or can I include it in my gradle project? Thanks!

@spkingr, could you, please, give an example of import in gradle for JKid. I still have problems with understanding what should I place in implementation in gradle(

**Comment by spkingr** [comment]
@InspectorZheleshka  Look this: https://jitpack.io/#yole/jkid/ec66c0b13c

**Comment by MisterDerpie** [comment]
FYI as I stumbled over that today:

1. To include `jitpack`:
```
repositories {
    ...
    maven { url = uri("https://jitpack.io") }
}
```
Source [Stackoverflow - CommonsWare](https://stackoverflow.com/a/63332349)

2. jkid:
```
dependencies {
    ...
    implementation("com.github.yole:jkid:60ec0e3284")
}
```

Note that in Kotlin Gradle you use `"` instead of `'`
